[package]
name = "ledgence-adapter-http"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
publish = false

[features]
default = []
client = ["dep:reqwest"]
completion = ["dep:reqwest"]
server = ["dep:axum", "dep:http-body-util"]

[dependencies]
ledgence-orchestration-api.workspace = true
ledgence-worker-api.workspace = true
serde.workspace = true
serde_json.workspace = true
tokio.workspace = true
tracing.workspace = true
reqwest = { workspace = true, optional = true }
axum = { workspace = true, optional = true }
http-body-util = { version = "0.1.3", optional = true }

[dev-dependencies]
tracing-subscriber.workspace = true

[lints]
workspace = true
